### ISSUE TITLE
Switching input source in MacOS 12 does not work

### ISSUE THREAD

**Issue by stefanhgm** [patrick-zippenfenig/us-with-german-umlauts#4]
Hi,

first of all, thank you very much for creating this nice workaround!

I am using a new MacBook Pro M1 witch MacOS 12. I followed your installing instructions and I have the input source selector in the top bar containing you new source. However, there is a weird behavior that in several applications MacOS automatically switches back to the default "ABC" source. In the system preferences search field, for instance, I can use your input with the intended behavior. In Mail and Safari MacOS switches to "ABC" and I cannot use your shortcuts. Any idea what might cause this behavior?

Cheers

**Comment by patrick-zippenfenig** [comment]
Hi,

in settings for keyboard -> input sources there is a checkmark for `Automatically switch to a document's input source` which should be turned off.

Otherwise I noticed this behaviour only after a fresh first time install. After a reboot it worked for me consistently.

<img width="780" alt="Screenshot 2021-11-21 at 19 06 57" src="https://user-images.githubusercontent.com/11670456/142773814-01c2ea78-c9b1-4aaa-ad5c-de6dd77c4aff.png">

Best, Patrick

**Comment by stefanhgm** [comment]
Another reboot fixed it. Now it works like a charm. Thanks again!

**Comment by kgroshert** [comment]
MacOS 12.5.1 here, it worked for some apps and not for others (mostly MS Office). After the second reboot everything worked, don't know why. Thanks for creating this!
